### ISSUE TITLE
Consumer demand not growing in the Microscaling UI

### ISSUE THREAD

**Issue by sauryadas** [microscaling/queue-demo#6]
Following documentation here [https://dcos.io/docs/1.7/usage/tutorials/autoscaling/microscaling-queue/](url)

I do not see the consumer demand grow and shrink in the UI .. it remains flat even when I have scaled the producer up to 10 . I checked the queue length using the Azure CLI and there are messages.
any idea what I am missing?

![123](https://cloud.githubusercontent.com/assets/15387759/16069315/45943b76-3282-11e6-8c33-70f0244b60fe.jpg)

![345](https://cloud.githubusercontent.com/assets/15387759/16069327/5e7bee54-3282-11e6-9d01-e18ed459c5d2.jpg)

**Comment by rossf7** [comment]
Thanks for trying the demo but I'm sorry you've hit this issue. I think the problem is that the queue name isn't matching. It expects the queue to be called microscaling-demo and puts that in the AZURE_STORAGE_QUEUE_NAME env var. I think the queue length is showing as 0 because its checking the wrong queue.

You can change this by going to the Configure page and clicking "Edit Rule". Does that fix it?

From re-reading the DCOS tutorial I think we need to make it clearer what the queue name should be. If this is the problem we'll get that fixed.

**Comment by sauryadas** [comment]
Thanks... indeed the queue name was a problem.. i will make a PR as i need other edits .... this is a great demo....
